### ISSUE TITLE
jumping back

### ISSUE THREAD

**Issue by CloudyMushroom** [CoteriePH/ikeep-metamask#1]
once na magclick ng back dito
![image](https://user-images.githubusercontent.com/74799765/155880612-7acfead0-0008-4fdd-81e2-54bfb4822f75.png)

magaappear siya sa inaappropriate windows
such as:
![image](https://user-images.githubusercontent.com/74799765/155880652-8daeace7-31d9-4e7a-b854-b9e167a6a8b2.png)

or sa creating an account window if di yung user di pa nakakapag view ng na insert niyang account

**Comment by EricEchemane** [comment]
Pa check ulit ako sir, I think okay na siya
