### ISSUE TITLE
Customize/Edit Account

### ISSUE THREAD

**Issue by yell66w** [CoteriePH/ikeep-metamask#2]
Suggestion ko lang po kung pwede nakalagay na agad yung image tsaka yung nickname ng user sa edit page po. 
Para kung example, gusto niya lang ichange yung nickname, hindi nya na ichachange yung image.
Optional lang po ito hehe

![Screenshot_20220228_172012](https://user-images.githubusercontent.com/37836505/155957163-3f234569-b3e3-4d43-be36-b67bbe56dca0.png)

**Comment by EricEchemane** [comment]
oks na sir implemented na...Good idea HAHA
