### ISSUE TITLE
Edit Modal

### ISSUE THREAD

**Issue by yell66w** [CoteriePH/ikeep-metamask#4]
Yung katapos po iedit yung account, mali po ata yung nakalagay sa title kasi created po nakalagay tsaka yung description.
![Screenshot_20220228_172816](https://user-images.githubusercontent.com/37836505/155958685-11e0d0ed-c223-4a8c-b58f-475b184a0f53.png)

**Comment by EricEchemane** [comment]
Fixed na sir
